### PR TITLE
Add rel="noopener" to target="_blank" links

### PR DESCRIPTION
**Pull request by christianbundy**
This adds [`rel="noopener"`](https://mathiasbynens.github.io/rel-noopener/) to our outbound links to stop a bug where webpages we link to can change our `window.location` (!).

Alternatively, maybe we should remove `target="_blank"`?

### CODE REVIEW

**Comment by dominictarr** [comment]
please, as a policy, include at least a description of why the change is desirable, I guess if it's just a typo it's okay, but don't assume it's obvious... I've never heard of `rel=noopener` before. otherwise there is a tendency to be like "shrug. if @christianbundy wants this it's probably a good idea" but then you arn't spreading any knowledge around, so the code starts to implicitly depend on stuff inside your head. Speaking as someone who has lots of code that depends on stuff implicitly inside my head, you probably don't want to be in this situation.

**Comment by christianbundy** [comment]
@dominictarr  Sorry about that, I added info in the code comments but totally should've done it in the PR description. Should be ready for a review now.

**Comment by dominictarr** [comment]
that link is good... but it doesn't have a simple TLDR, which means someone merging this has to actually read it and understand it. You should really make this as easy as possible by including a short TLDR (if the article doesn't)

Also if it's important you should indicate that like this is a security fix! but you didn't say it was a security fix! something like: "security fix: without rel=noopener, pages opened when the user clicks a link have access to this page's `window`, if they are cross origin they still have write access to window.location (!!!)"

I'm honestly quite shocked to learn about this browser-wart!

**Comment by dominictarr** [comment]
with respect to this issue: please merge!

**Pull request merged**
