### PR TITLE
Fix HTML leakage in markdown.inline

### PR DESCRIPTION
**Pull request by clehner**
In the Patchwork newsfeed, in Large or Compact view (which use `markdown.inline`), some HTML can be seen to leak from the markdown. For example, find <http://localhost:7777/#/msg/%25NpEZzVHrfVlS8QW%2BtyJPUGmWbWh3x2O6MIgdxQK%2F0xI%3D.sha256> in the #modules channel <http://localhost:7777/#/newsfeed/channel/modules>.

2016-01-19-200335_1280x800_scrot

### CODE REVIEW

**Comment by clehner** [comment]
Converted the issue to a pull request; ready for review. This also includes minor updates to the testing code and to package.json.

**Comment by pfraze** [comment]
> Converted the issue to a pull request

I didnt know you could do that!

**Comment by clehner** [comment]
> Converted the issue to a pull request
>> I didnt know you could do that!

It might not always be the best way, but here's a tool to help do it in the future:
https://gist.github.com/clehner/5cf0af6d96321a36e94c

**Comment by pfraze** [comment]
Cool.

So this looks good except the quote/unquote functions are now pretty confusing. I wish I documented why I did unquote, originally, because now I'm looking and I'm not sure.

Let's go ahead and merge this, and I'll put on my todo list to go back and clean this up. :+1:

**Comment by pfraze** [comment]
Published `1.0.1`

**Comment by clehner** [comment]
Cool!

**Pull request merged**
