### PR TITLE
Pass all links through toUrl()

### LINKED ISSUE #33: v4 broke message links on yap (and probably other http based clients, if they used it)
before 4, ssb-markdown called `toUrl(id)` on a message link i.e. `[link text](%<id>)` but not in v4. This doesn't effect front-end js clients like patchbay, because they use invalid urls internally and have a clickhandler.

yap needs to [transform the message id into a valid url](https://github.com/dominictarr/yap/blob/master/util.js#L188)

I'm not sure _exactly_ where this happens though.

### PR DESCRIPTION
**Pull request by christianbundy**
Resolves #33, although this looks like it should technically be a breaking change (since we're passing all links through `toUrl()`.

@dominictarr Does this look right to you?

### CODE REVIEW

**Comment by dominictarr** [comment]
this definitely seems to be a breaking change, I tried running this code through yap and all the msg links became `http://localhost:8005/false`

**Comment by dominictarr** [comment]
channel links are okay though

**Comment by christianbundy** [comment]
Yeah I had to change my toUrl() function, previously it was returning empty string so if the URLs didn't match and SSB refs then they were getting removed altogether. Are you returning false in that case? I only changed one line in the test code.

**Comment by dominictarr** [comment]
hmm, looking again at my code: https://github.com/dominictarr/yap-util/blob/master/index.js#L195-L208

obviously it's passing in something that `ref.parseLink` isn't liking... oh, no, before if it returns false, it fell back to the original link. Would that be okay? It's also just a one line change to my code, but might as well not make a breaking change unless really necessary, right?

**Comment by christianbundy** [comment]
Good idea! I just pushed a change that's basically `href = toUrl(href) || href`, does that work? That should keep it backward-compatible.

**Comment by dominictarr** [comment]
oh I noticed another quirk. if you put a ssb msg id inside a markdown link, it gets URI encoded, but if you just paste it in it doesn't.

this message has several nice links `%sf/03+phEMlMFJGHWOLvSSovxc2RPZKD4y7cMwyGctg=.sha256`
this message just has a raw link: `%qcdW859vSp/bQCA8qiPsirrCrjlIUHeq80QRjhCKYvU=.sha256`
backwards compatible is to decode uris before calling toUrl

**Pull request merged**
