### PR TITLE
Backcompat tests

### PR DESCRIPTION
**Pull request by dominictarr**
@christianbundy I added a few tests to check that toUrl was backwards compatible, they are currently failing.

they also cover the quirk I [described here](https://github.com/ssbc/ssb-markdown/pull/43#issuecomment-506232792)

Also, turns out a raw link is passed to toUrl _TWICE_ once as the raw link, then again as the url that was first returned.

### CODE REVIEW

**Comment by christianbundy** [comment]
Thanks for writing these tests. I pushed a commit with a solution to the new problems, but it breaks some weird(?) legacy handling of raw sigil links and @mentions. More info in my commit message, I'd love feedback on what the right solution is here.

**Comment by dominictarr** [comment]
Okay cool. I think the most important thing is that everything is handled consistently.
I suggest that the guide should be that a raw link is handled exactly the same as if it was a markdown link `%{msg_id}` does the same thing as `[%{truncated_msg_id}...](%{msg_id})` including making the same call to toUrl and outputting the same html.

but what should that behaviour be, exactly?

**Comment by christianbundy** [comment]
I should've updated, but I pushed another commit that passes all of the tests.

I think what it's currently doing is *mostly* fine, my only nitpicks are that `target="_blank"` is a pain I'd prefer to stop fighting against `decodeURI()`, but I think the Electron clients might depend on those. :man_shrugging:

**Comment by christianbundy** [comment]
Looks like this now fails on sigil links that starts with `%25`. :roll_eyes:

**Comment by christianbundy** [comment]
Feeling much better about this now:

- `toUrl()` is called in one place and one place only
- the hacky pre-processed link crap is removed because it's no longer necessary
- we're using `try...catch` in case `decodeURI()` is passed a malformed URI (some sigil links that *look* like URL-encoded strings but are really not)

I'm using this in my client now and it seems to be working great. :tada:

**Pull request merged**
