### PR TITLE
add option to link images & add .gitignore

### PR DESCRIPTION
**Pull request by mixmix**
This adds the option to have image tags have a custom href.

This is so Patchbay images can open easily in new tabs. 
Smoke tested over there and works fine.

### CODE REVIEW

**Comment by arj03** [comment]
Spicy! This is really missing, can't see the nice wedding pictures in full size.

**Comment by mixmix** [comment]
@dominictarr would love to get this in. 
I think the interface feels right, open to changes in name for the option if you can think of something better.

**Comment by dominictarr** [comment]
merged into 3.2.0 also added you as npm owner @mixmix

**Comment by mixmix** [comment]
thanks !

**Pull request merged**
