### PR TITLE
support ssb-markdown@3 style toUrl option

### LINKED ISSUE #33: v4 broke message links on yap (and probably other http based clients, if they used it)
before 4, ssb-markdown called `toUrl(id)` on a message link i.e. `[link text](%<id>)` but not in v4. This doesn't effect front-end js clients like patchbay, because they use invalid urls internally and have a clickhandler.

yap needs to [transform the message id into a valid url](https://github.com/dominictarr/yap/blob/master/util.js#L188)

I'm not sure _exactly_ where this happens though.

### PR DESCRIPTION
**Pull request by dominictarr**
@christianbundy this resolves #33 (I have confirmed it works) I consider this a hack, but I don't have time to do a proper fix right now.

### CODE REVIEW

**Comment by dominictarr** [comment]
it breaks the tests, but works when linked into yap

**Comment by dominictarr** [comment]
@christianbundy bump?

**Comment by christianbundy** [comment]
Bump received, what's up?

I don't think we should merge this until we have the tests passing again. I don't have time today to implement another fix for this but I might have some time later this week.

**Comment by christianbundy** [comment]
Resolved in #44

**Pull request closed without merging**
