### PR TITLE
Make inline images clickable links

### PR DESCRIPTION
**Pull request by pfraze**
Can now click on an embedded image and it'll take you to the image

### CODE REVIEW

**Comment by pfraze** [comment]
published `1.1.1`

**Comment by dominictarr** [comment]
this was a breaking change when using within electron.

**Comment by dominictarr** [comment]
https://github.com/ssbc/ssb-markdown/issues/6

**Comment by dominictarr** [comment]
the breakingness was clearly accidential now that I see it though, so the solution is to fix it with another patch.

**Pull request merged**
