### PR TITLE
Allow others protocols to be parsed as links

### PR DESCRIPTION
**Pull request by gmarcos87**
Check if the url belongs to a protocol specified in the options. If so, you can render the link.

Related to #11 ssbc/patchwork#616

### CODE REVIEW

**Comment by dominictarr** [comment]
this just adds dat support, right? I'm guessing that clicking on one of these links will just open whatever app is registered with the OS as the dat provider?

**Comment by gmarcos87** [comment]
Not only dat, but the protocols you want. You just have to pass the prefix in an array in the options. The operating system is responsible for opening the application associated with each one. If this change is approved I have another in mind for patchcore, then protocols can be established via depject, at the discretion of each client.

**Comment by gmarcos87** [comment]
ping. Please merge or close.
Thanks

**Comment by dominictarr** [comment]
merged into 3.5.0

**Pull request merged**
