### PR TITLE
revert localhost:7777

### LINKED ISSUE #6: 1.1.1 was a breaking change
I tried patchwork 2.3.1, then went back to an old version, but on reinstalling, I couldn't see any images.
Luckily I guessed that this had changed and I was right.

This should have been published as 2.0.0

really, the way that images (etc) are linked should be set by the user of this module (so it could potentially be reused in other apps).

### PR DESCRIPTION
**Pull request by dominictarr**
sorry, I over reacted before. this fixes #6

### CODE REVIEW

**Comment by pfraze** [comment]
Huh, are you sure? i dont experience any problems in electron; do you see a CSP error in the console?

The reason for the change was, browsers treat `127.0.0.1` as a different origin than `localhost`, so the CSP rule `self` was failing if you opened Patchwork via `127.0.0.1`.

**Comment by dominictarr** [comment]
I went back to my ssb-names pr, that was based on a month old patchwork, your latest commit. 2e4f687049ef61928e1f6cfa8eada0e74ab3f5f8

**Comment by dominictarr** [comment]
but since the location is patchwork is a file, it tries to open `file:///{bloblink}` which doesn't work.

**Comment by pfraze** [comment]
Right, you'll need to merge master into your ssb-names PR, because Electron changed to loading the index.html over HTTP.

**Comment by pfraze** [comment]
That does indicate that this is a breaking change, though. Should we merge this, publish as a patch, and then "unmerge" this and publish major?

**Comment by dominictarr** [comment]
@pfraze that would be sufficient.

**Comment by pfraze** [comment]
Done, versions `1.1.2` and `2.0.0`

**Comment by dominictarr** [comment]
sweet!

**Pull request merged**
