### PR TITLE
Update hashtag regex

### LINKED ISSUE #34: Make the markdown renderer include non-ascii characters in channel names
The title is maybe a bit unclear but my specific problem is that when you make a message saying "#malmö" it only renders "#malm" as clickable (and it takes you to the malm channel).

Everything else around this seems to work fine, I can go to the channel using the search box, subscribe to it, and the post linking "#malm"(ö) even ends up in the "#malmö" channel.

I have a feeling this is going to have to be fixed in a dep but I haven't had time to look into that yet.

### PR DESCRIPTION
**Pull request by qubist**
This fixes #34 special characters messing up channel links

### CODE REVIEW

**Comment by qubist** [comment]
http://unicode.org/reports/tr31/#hashtag_identifiers

**Comment by christianbundy** [comment]
I dig this! I'm very supportive of using the Unicode hashtag spec. IIRC the spec says that we need to disallow `#` characters from hashtags, so `#this#hashtag#is#invalid` should be invalid, but otherwise I think this looks great. I'll ping some other butts to get opinions because this would be hard to undo in the future.

**Comment by qubist** [comment]
@christianbundy I think the current behavior is that a `#` character starts a new hashtag, so `#this#hashtag#is#invalid` isn't invalid, but it is four hashtags next to each other without spaces in between them.

Regex example: https://regex101.com/r/Gk9tLO/1/

The exact regex in that example is modified a bit to be parsed correctly by regex101. I changed some `\`s and put a `#` in front of the version in the code. But should be logically the same, as long as `markdown-it-hashtag` treats actually searching for the initial `#` the same way that this example regex does.

**Comment by qubist** [comment]
But yes let's be thorough as this change will be located pretty far up towards the headwaters :)

**Comment by christianbundy** [comment]
Oh, cool! Thanks for correcting me, that's great. I noticed a while ago that there's also the [unicode-hashtag-regex](https://github.com/mathiasbynens/hashtag-regex) as an npm package -- do you have any opinions on using that package vs rolling our own? The [implementation](https://github.com/mathiasbynens/hashtag-regex/blob/e8e45e27d40b0d0bf3ef0ecf038de77aa832fe72/src/index.js#L2) is tiny but I like that it's got its own tests and such. What do you think?

**Comment by noffle** [comment]
I'd feel even better with some tests, that poke at edge cases like these.

**Comment by qubist** [comment]
> do you have any opinions on using that package vs rolling our own?

If we can pull this in and get it to work with `markdown-it-hashtag`, that would be amazing. But in my research I found that it's not possible to use the regex syntax that this package uses in JavaScript.
```javascript
 /<% Start %>(?:<% Continue %>)+/gu
```
or
```javascript
/[#\uFF03][\p{XID_Continue}_\p{Emoji}]+/gu
```
I found that the curly-braces syntax doesn't work to reference Unicode categories in Javascript, and the only way to interact with Unicode stuff is by codepoint using `\u`. I've never even heard of this `<% Start %>` syntax.

If in fact this package will integrate nicely with `markdown-it-hashtag`, it seems to me like the way to go.

Another thing: I couldn't figure out how to launch patchwork/patchbay using a different version of ssb-markdown, so I couldn't test the change. I'd love help with that process.

**Comment by christianbundy** [comment]
Oops, I should've realized that those were just template tags. The real regex gets added from [this file](https://github.com/mathiasbynens/hashtag-regex/blob/master/script/inject-sequences.js). You're right, it looks like markdown-it-hashtag hardcodes the hashtag symbol so we'll have to do some fancy text substitution to hack that out. I've opened a PR into your branch as https://github.com/qubist/ssb-markdown/pull/1 for your consideration. :upside_down_face:

**Comment by christianbundy** [comment]
> Another thing: I couldn't figure out how to launch patchwork/patchbay using a different version of ssb-markdown, so I couldn't test the change. I'd love help with that process.

You can use [`npm link`](https://docs.npmjs.com/cli/link) for this, *or* you can edit `package.json` to set `{ "ssb-markdown": "github:qubist/ssb-markdown#master }` and run `npm install`.

**Comment by mixmix** [comment]
Let me know if I'm needed Christian. Seems like there are a bunch of butts
on board with this.
Please DM me on ssb or signal - I currently suck at email

**Pull request merged**
