### PR TITLE
add '?' to the list of recognised sigils

### PR DESCRIPTION
**Pull request by mmckegg**
This way you can link to searches!

### CODE REVIEW

**Comment by ahdinosaur** [comment]
oh wow cool! how would this work for searching multiple words or a phrase?

**Comment by mmckegg** [comment]
@ahdinosaur I was just going to use it in urls. e.g. `[look at this search](?some cool search)`.

`markdown-ssb` is sanitizing the urls and removing ones that don't start with a recognised sigil.

**Comment by ahdinosaur** [comment]
oh okay sweet :+1:

**Comment by mixmix** [comment]
Niiiice. This reminds me of that conversation about asking friends to
extend your search. As in -  could you click this and paste for good
results in whatever filtered social sphere you're running plz. This feels
like a tangible first step to that

**Comment by mixmix** [comment]
Next one would be showing results which you know the person who posted it
DOESN'T likely have (because they're not in follow range)

**Pull request closed without merging**
